openapi: "3.0.0"
info:
  version: 1.0.0
  title: BLOBS Swagger Documentation
  contact:
  name: Ardi Goxhaj
  email: goxhaj@gmail.com
license:
  name: Apache 2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /blobs:
    post:
      summary: Create a Blob
      operationId: createBlob
      tags:
        - blobs
      requestBody:
        description: A JSON object containing Blob request information
        content:
          application/json:
            schema:
              type: object
              properties:
                callback_url:   # Callback URL
                  type: string
                  format: uri
                  example: 	https://webhook.site/67679c5d-0e2a-47e6-8e73-1b53138bd617
      callbacks:   # Callback definition
        makeCallback:  
          '{$request.body#/callback_url}':   # The callback URL, refers to the passed URL
            post:
              requestBody:   # Contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/Blob"
              responses:   # Expected responses to the callback message
                '200':
                  description: Your server returns this code if it accepts the callback
      responses:
        '201':
          description: Valid Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blob"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /blobs/{blob_id}:
    get:
      summary: Info for a specific blob
      operationId: getBlobById
      tags:
        - blobs
      parameters:
        - name: blob_id
          in: path
          required: true
          description: The id of the blob to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Valid Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blob"
        '500':
          description: Internal Server Error 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /:
    put:
      summary: Put an image to S3 bucket
      description: This PUT method is used with the presigned_url generated by the POST /blobs to upload an image to S3 bucket
      servers:
          - url: presign_url
      responses:
        '200':
          description: The image was successfully uploaded
        '500':
          description: Internal Server Error 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
     
components:
  schemas:
    Blob:
      type: object
      required:
        - blob_id
        - callback_url
        - presigned_url
      properties:
        blob_id:
          type: string
        callback_url:
          type: string
        presigned_url:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string